[[repositories]]
name = ".vscode"
path = "."
url = "git@github.com:mirrorboards/mirrorboards-vscode.git"

[[repositories]]
name = "mirrorboards"
path = "mirrorboards"
url = "git@github.com:mirrorboards/mirrorboards-ts.git"

[[repositories]]
name = "mirrorboards-go"
path = "mirrorboards"
url = "git@github.com:mirrorboards/mirrorboards-go.git"

[[repositories]]
name = "mirrorboards-platform"
path = "."
url = "git@github.com:mirrorboards/platform.git"

[[repositories]]
name = "mirrorboards-fish-functions"
path = "mirrorboards-utils"
url = "git@github.com:mirrorboards/mirrorboards-fish-functions.git"

[[repositories]]
name = "mirrorboards-install"
path = "mirrorboards-utils"
url = "git@github.com:mirrorboards/mirrorboards-install.git"

[[repositories]]
name = "pay2vault-platform"
path = "."
url = "git@github.com:mirrorboards/pay2vault-platform.git"

[[repositories]]
name = "pay2vault-mobile"
path = "pay2vault"
url = "git@github.com:pay2vault/pay2vault-mobile.git"

[[repositories]]
name = "pay2vault-web"
path = "pay2vault"
url = "git@github.com:pay2vault/pay2vault-web.git"

[[repositories]]
name = "pay2vault-api"
path = "pay2vault"
url = "git@github.com:pay2vault/pay2vault-api.git"

[[repositories]]
name = "exchange-operations"
path = "exchange"
url = "git@github.com:mirrorboards-exchange/mirrorboards-exchange-operations.git"

[[repositories]]
name = "exchange-platform"
path = "."
url = "git@github.com:mirrorboards-exchange/mirrorboards-exchange-platform.git"

[[repositories]]
name = "mirrorboards"
path = "mirrorboards"
url = "git@github.com:mirrorboards/mirrorboards.git"

[[repositories]]
name = "mirrorboards-mctl"
path = "mirrorboards-utils"
url = "git@github.com:mirrorboards/mirrorboards-mctl.git"
